"""empty message

Revision ID: 11ea42513c7
Revises: 1ec080a258c
Create Date: 2015-05-24 11:22:50.383265

"""

# revision identifiers, used by Alembic.
revision = '11ea42513c7'
down_revision = '1ec080a258c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
