"""empty message

Revision ID: 12e9319a3b2
Revises: cf6d5361f5
Create Date: 2015-06-09 22:43:20.542388

"""

# revision identifiers, used by Alembic.
revision = '12e9319a3b2'
down_revision = 'cf6d5361f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
