"""empty message

Revision ID: 141da405110a
Revises: 4703ef9dff17
Create Date: 2015-05-29 02:52:13.430197

"""

# revision identifiers, used by Alembic.
revision = '141da405110a'
down_revision = '4703ef9dff17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
