"""empty message

Revision ID: 16de54202447
Revises: 3e294b6ddb05
Create Date: 2015-05-28 11:03:19.976671

"""

# revision identifiers, used by Alembic.
revision = '16de54202447'
down_revision = '3e294b6ddb05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
