"""empty message

Revision ID: 1712b28d156
Revises: 17750c498f0
Create Date: 2015-06-08 19:06:30.499836

"""

# revision identifiers, used by Alembic.
revision = '1712b28d156'
down_revision = '17750c498f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
