"""empty message

Revision ID: 17750c498f0
Revises: 36d3c2eca8
Create Date: 2015-06-08 15:57:00.376029

"""

# revision identifiers, used by Alembic.
revision = '17750c498f0'
down_revision = '36d3c2eca8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
