"""empty message

Revision ID: 188caee076f
Revises: 4f44b9cc71c
Create Date: 2015-05-22 15:26:03.992172

"""

# revision identifiers, used by Alembic.
revision = '188caee076f'
down_revision = '4f44b9cc71c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
