"""empty message

Revision ID: 1abb55096bf
Revises: 7e3b41bc0d
Create Date: 2015-06-02 15:44:14.356029

"""

# revision identifiers, used by Alembic.
revision = '1abb55096bf'
down_revision = '7e3b41bc0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
