"""empty message

Revision ID: 1b06eead3a
Revises: 2b171ef11a6
Create Date: 2015-06-04 13:27:18.929753

"""

# revision identifiers, used by Alembic.
revision = '1b06eead3a'
down_revision = '2b171ef11a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
