"""empty message

Revision ID: 1e1dbad757
Revises: 1abb55096bf
Create Date: 2015-06-02 15:47:13.272333

"""

# revision identifiers, used by Alembic.
revision = '1e1dbad757'
down_revision = '1abb55096bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
