"""empty message

Revision ID: 1e8403693fb
Revises: 271c979d08c
Create Date: 2015-06-02 17:41:39.592365

"""

# revision identifiers, used by Alembic.
revision = '1e8403693fb'
down_revision = '271c979d08c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
