"""empty message

Revision ID: 1ec080a258c
Revises: 4f1c1a77810
Create Date: 2015-05-24 11:20:41.874409

"""

# revision identifiers, used by Alembic.
revision = '1ec080a258c'
down_revision = '4f1c1a77810'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
