"""empty message

Revision ID: 1fa9a327649
Revises: 2530514d4ca
Create Date: 2015-06-12 19:42:53.513504

"""

# revision identifiers, used by Alembic.
revision = '1fa9a327649'
down_revision = '2530514d4ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
