"""empty message

Revision ID: 2530514d4ca
Revises: 5a546437537
Create Date: 2015-06-11 13:37:41.270917

"""

# revision identifiers, used by Alembic.
revision = '2530514d4ca'
down_revision = '5a546437537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dpt')
    op.drop_table('role')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('idrole', sa.INTEGER(), server_default=sa.text("nextval('role_idrole_seq'::regclass)"), nullable=False),
    sa.Column('namerole', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idrole', name='role_pkey'),
    sa.UniqueConstraint('namerole', name='role_namerole_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dpt',
    sa.Column('iddpt', sa.INTEGER(), server_default=sa.text("nextval('dpt_iddpt_seq'::regclass)"), nullable=False),
    sa.Column('namedpt', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('iddpt', name='dpt_pkey'),
    sa.UniqueConstraint('namedpt', name='dpt_namedpt_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('fullname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('iddpt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idrole', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iddpt'], ['dpt.iddpt'], name='user_iddpt_fkey'),
    sa.ForeignKeyConstraint(['idrole'], ['role.idrole'], name='user_idrole_fkey'),
    sa.PrimaryKeyConstraint('username', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('idrole', name='user_idrole_key')
    )
    ### end Alembic commands ###
