"""empty message

Revision ID: 271c979d08c
Revises: 1e1dbad757
Create Date: 2015-06-02 17:04:17.430682

"""

# revision identifiers, used by Alembic.
revision = '271c979d08c'
down_revision = '1e1dbad757'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
