"""empty message

Revision ID: 2abef352fff
Revises: 188caee076f
Create Date: 2015-05-24 09:19:26.645832

"""

# revision identifiers, used by Alembic.
revision = '2abef352fff'
down_revision = '188caee076f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
