"""empty message

Revision ID: 2b171ef11a6
Revises: None
Create Date: 2015-06-04 12:45:25.912609

"""

# revision identifiers, used by Alembic.
revision = '2b171ef11a6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
