"""empty message

Revision ID: 2d0856a5987
Revises: 4c37728d918
Create Date: 2015-06-03 11:53:16.871455

"""

# revision identifiers, used by Alembic.
revision = '2d0856a5987'
down_revision = '4c37728d918'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
