"""empty message

Revision ID: 2e66baeed04
Revises: 5a546437537
Create Date: 2015-06-10 19:10:03.782987

"""

# revision identifiers, used by Alembic.
revision = '2e66baeed04'
down_revision = '5a546437537'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
