"""empty message

Revision ID: 31b4cbd9baa5
Revises: 141da405110a
Create Date: 2015-06-02 21:42:40.631125

"""

# revision identifiers, used by Alembic.
revision = '31b4cbd9baa5'
down_revision = '141da405110a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
