"""empty message

Revision ID: 34bb98ec2b2
Revises: 3d05ffda070
Create Date: 2015-05-29 10:30:21.857582

"""

# revision identifiers, used by Alembic.
revision = '34bb98ec2b2'
down_revision = '3d05ffda070'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
