"""empty message

Revision ID: 36d3c2eca8
Revises: 88418304e5
Create Date: 2015-06-08 15:28:30.574323

"""

# revision identifiers, used by Alembic.
revision = '36d3c2eca8'
down_revision = '88418304e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
