"""empty message

Revision ID: 39c79884b3c
Revises: 467249e9ac0
Create Date: 2015-06-08 20:58:21.057377

"""

# revision identifiers, used by Alembic.
revision = '39c79884b3c'
down_revision = '467249e9ac0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
