"""empty message

Revision ID: 3d05ffda070
Revises: 141da405110a
Create Date: 2015-05-29 09:53:19.490912

"""

# revision identifiers, used by Alembic.
revision = '3d05ffda070'
down_revision = '141da405110a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
