"""empty message

Revision ID: 3d9102f239b
Revises: c6fbb1a586
Create Date: 2015-06-03 17:34:50.962295

"""

# revision identifiers, used by Alembic.
revision = '3d9102f239b'
down_revision = 'c6fbb1a586'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
