"""empty message

Revision ID: 3def7c20398
Revises: 4758438ba2c
Create Date: 2015-06-03 11:23:53.497027

"""

# revision identifiers, used by Alembic.
revision = '3def7c20398'
down_revision = '4758438ba2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
