"""empty message

Revision ID: 3e294b6ddb05
Revises: 11ea42513c7
Create Date: 2015-05-28 10:07:07.460145

"""

# revision identifiers, used by Alembic.
revision = '3e294b6ddb05'
down_revision = '11ea42513c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
