"""empty message

Revision ID: 3ede8ca36ae
Revises: 53dc761c96d
Create Date: 2015-06-04 16:34:06.850185

"""

# revision identifiers, used by Alembic.
revision = '3ede8ca36ae'
down_revision = '53dc761c96d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
