"""empty message

Revision ID: 3f6699c0310
Revises: 48fbb70617d
Create Date: 2015-06-08 11:39:59.060832

"""

# revision identifiers, used by Alembic.
revision = '3f6699c0310'
down_revision = '48fbb70617d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
