"""empty message

Revision ID: 42800bfc7ea
Revises: 34bb98ec2b2
Create Date: 2015-06-01 11:12:21.069478

"""

# revision identifiers, used by Alembic.
revision = '42800bfc7ea'
down_revision = '34bb98ec2b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
