"""empty message

Revision ID: 444e0ad27c8
Revises: 2d0856a5987
Create Date: 2015-06-03 16:57:31.114345

"""

# revision identifiers, used by Alembic.
revision = '444e0ad27c8'
down_revision = '2d0856a5987'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
