"""empty message

Revision ID: 4585b74fc02
Revises: 39c79884b3c
Create Date: 2015-06-09 22:28:03.655135

"""

# revision identifiers, used by Alembic.
revision = '4585b74fc02'
down_revision = '39c79884b3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
