"""empty message

Revision ID: 467249e9ac0
Revises: 1712b28d156
Create Date: 2015-06-08 19:10:12.285162

"""

# revision identifiers, used by Alembic.
revision = '467249e9ac0'
down_revision = '1712b28d156'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
