"""empty message

Revision ID: 4703ef9dff17
Revises: 11ea42513c7
Create Date: 2015-05-29 02:50:37.390975

"""

# revision identifiers, used by Alembic.
revision = '4703ef9dff17'
down_revision = '11ea42513c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
