"""empty message

Revision ID: 471841895a8
Revises: 1b06eead3a
Create Date: 2015-06-04 15:48:55.728233

"""

# revision identifiers, used by Alembic.
revision = '471841895a8'
down_revision = '1b06eead3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
