"""empty message

Revision ID: 4758438ba2c
Revises: 31b4cbd9baa5
Create Date: 2015-06-03 07:59:21.989425

"""

# revision identifiers, used by Alembic.
revision = '4758438ba2c'
down_revision = '31b4cbd9baa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
