"""empty message

Revision ID: 48b225450e3
Revises: 4585b74fc02
Create Date: 2015-06-09 22:30:57.241582

"""

# revision identifiers, used by Alembic.
revision = '48b225450e3'
down_revision = '4585b74fc02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
