"""empty message

Revision ID: 48fbb70617d
Revises: 3ede8ca36ae
Create Date: 2015-06-07 20:37:52.849455

"""

# revision identifiers, used by Alembic.
revision = '48fbb70617d'
down_revision = '3ede8ca36ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
