"""empty message

Revision ID: 4c37728d918
Revises: 3def7c20398
Create Date: 2015-06-03 11:43:24.191876

"""

# revision identifiers, used by Alembic.
revision = '4c37728d918'
down_revision = '3def7c20398'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
