"""empty message

Revision ID: 4f1c1a77810
Revises: 2abef352fff
Create Date: 2015-05-24 11:12:39.092352

"""

# revision identifiers, used by Alembic.
revision = '4f1c1a77810'
down_revision = '2abef352fff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
