"""empty message

Revision ID: 4f44b9cc71c
Revises: None
Create Date: 2015-05-22 15:01:23.607317

"""

# revision identifiers, used by Alembic.
revision = '4f44b9cc71c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
