"""empty message

Revision ID: 4f787df6144
Revises: None
Create Date: 2015-05-28 16:25:16.565968

"""

# revision identifiers, used by Alembic.
revision = '4f787df6144'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
