"""empty message

Revision ID: 53dc761c96d
Revises: 1b06eead3a
Create Date: 2015-06-04 14:52:06.623903

"""

# revision identifiers, used by Alembic.
revision = '53dc761c96d'
down_revision = '1b06eead3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
