"""empty message

Revision ID: 553250cf6ac
Revises: 56fa14cf780
Create Date: 2015-06-08 12:47:25.146766

"""

# revision identifiers, used by Alembic.
revision = '553250cf6ac'
down_revision = '56fa14cf780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
