"""empty message

Revision ID: 56a53ae5fdd
Revises: f8505b8cda
Create Date: 2015-06-08 12:16:53.646624

"""

# revision identifiers, used by Alembic.
revision = '56a53ae5fdd'
down_revision = 'f8505b8cda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
