"""empty message

Revision ID: 56fa14cf780
Revises: 56a53ae5fdd
Create Date: 2015-06-08 12:19:41.901226

"""

# revision identifiers, used by Alembic.
revision = '56fa14cf780'
down_revision = '56a53ae5fdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
