"""empty message

Revision ID: 5a546437537
Revises: 12e9319a3b2
Create Date: 2015-06-10 07:59:08.699538

"""

# revision identifiers, used by Alembic.
revision = '5a546437537'
down_revision = '12e9319a3b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
