"""empty message

Revision ID: 7e3b41bc0d
Revises: 141da405110a
Create Date: 2015-06-02 15:39:33.160772

"""

# revision identifiers, used by Alembic.
revision = '7e3b41bc0d'
down_revision = '141da405110a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
