"""empty message

Revision ID: 87e3b3bbb56
Revises: 4f787df6144
Create Date: 2015-05-28 16:57:00.280312

"""

# revision identifiers, used by Alembic.
revision = '87e3b3bbb56'
down_revision = '4f787df6144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
