"""empty message

Revision ID: 88418304e5
Revises: 553250cf6ac
Create Date: 2015-06-08 12:49:39.677471

"""

# revision identifiers, used by Alembic.
revision = '88418304e5'
down_revision = '553250cf6ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
