"""empty message

Revision ID: c6fbb1a586
Revises: 4758438ba2c
Create Date: 2015-06-03 15:14:52.370339

"""

# revision identifiers, used by Alembic.
revision = 'c6fbb1a586'
down_revision = '4758438ba2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
