"""empty message

Revision ID: cf6d5361f5
Revises: 48b225450e3
Create Date: 2015-06-09 22:37:09.825839

"""

# revision identifiers, used by Alembic.
revision = 'cf6d5361f5'
down_revision = '48b225450e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
