"""empty message

Revision ID: f8505b8cda
Revises: 3f6699c0310
Create Date: 2015-06-08 12:15:38.839959

"""

# revision identifiers, used by Alembic.
revision = 'f8505b8cda'
down_revision = '3f6699c0310'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
